module.exports = {
  User: require("./User"),
  StudentProfile: require("./StudentProfile"),
  LandlordProfile: require("./LandlordProfile"),
  Property: require("./Property"),
  Review: require("./Review"),
  Message: require("./Message"),
  Conversation: require("./Conversation"),
  Notification: require("./Notification"),
  ListingReport: require("./ListingReport"),
  Listing: require("./Listing"),
  Plan: require("./Plan"),
  Payment: require("./Payment"),
  PaymentEvent: require("./PaymentEvent"),
  PaymentMethodSetting: require("./PaymentMethodSetting"),
  University: require("./University"),
  BookMark: require("./BookMark"),
  Schedule: require("./Schedule"),
};
